import { VocabSet, VocabItem } from '@/types/database'

export const INITIAL_MOCK_SETS: (VocabSet & { items: VocabItem[] })[] = [
  {
    id: 'ielts-core-01',
    user_id: 'demo-user',
    title: 'IELTS Core Vocabulary (Band 7.5+)',
    description: 'Bộ từ vựng học thuật quan trọng cho kỳ thi IELTS Speaking & Writing Task 2.',
    target_language: 'en',
    category: 'IELTS',
    is_public: true,
    created_at: '2026-01-01T00:00:00.000Z',
    item_count: 6,
    items: [
      {
        id: 'item-1',
        set_id: 'ielts-core-01',
        term: 'Resilience',
        definition: 'The capacity to recover quickly from difficulties; toughness.',
        ipa: '/rɪˈzɪl.jəns/',
        example_sentence: 'Her resilience helped her overcome severe challenges in her career.',
        vietnamese_translation: 'Khả năng phục hồi, sự kiên cường',
        synonyms: ['adaptability', 'toughness', 'flexibility'],
        created_at: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'item-2',
        set_id: 'ielts-core-01',
        term: 'Ubiquitous',
        definition: 'Present, appearing, or found everywhere.',
        ipa: '/juːˈbɪk.wə.təs/',
        example_sentence: 'Smartphones have become ubiquitous in modern human society.',
        vietnamese_translation: 'Phổ biến ở khắp mọi nơi',
        synonyms: ['omnipresent', 'pervasive', 'universal'],
        created_at: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'item-3',
        set_id: 'ielts-core-01',
        term: 'Meticulous',
        definition: 'Showing great attention to detail; very careful and precise.',
        ipa: '/məˈtɪk.jə.ləs/',
        example_sentence: 'The architect was meticulous in designing every single room of the building.',
        vietnamese_translation: 'Tỉ mỉ, cẩn thận từng chi tiết nhỏ',
        synonyms: ['thorough', 'diligent', 'precise'],
        created_at: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'item-4',
        set_id: 'ielts-core-01',
        term: 'Ameliorate',
        definition: 'Make something bad or unsatisfactory better.',
        ipa: '/əˈmiː.li.ə.reɪt/',
        example_sentence: 'New government policies aim to ameliorate living conditions in low-income areas.',
        vietnamese_translation: 'Cải thiện, làm cho tốt hơn',
        synonyms: ['improve', 'enhance', 'upgrade'],
        created_at: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'item-5',
        set_id: 'ielts-core-01',
        term: 'Pragmatic',
        definition: 'Dealing with things sensibly and realistically in a way that is based on practical considerations.',
        ipa: '/præɡˈmæt.ɪk/',
        example_sentence: 'We need a pragmatic approach to solving this complex technical issue.',
        vietnamese_translation: 'Thực tế, thực dụng',
        synonyms: ['practical', 'realistic', 'sensible'],
        created_at: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'item-6',
        set_id: 'ielts-core-01',
        term: 'Exacerbate',
        definition: 'Make a problem, bad situation, or negative feeling worse.',
        ipa: '/ɪɡˈzæs.ɚ.beɪt/',
        example_sentence: 'Heavy rain will exacerbate the flooding in urban regions.',
        vietnamese_translation: 'Làm trầm trọng thêm, làm tồi tệ hơn',
        synonyms: ['worsen', 'aggravate', 'intensify'],
        created_at: '2026-01-01T00:00:00.000Z',
      },
    ],
  },
  {
    id: 'toeic-business-02',
    user_id: 'demo-user',
    title: 'Business Communication Essentials',
    description: 'Từ vựng tiếng Anh thương mại sử dụng trong văn phòng và đàm phán.',
    target_language: 'en',
    category: 'Business',
    is_public: true,
    created_at: '2026-01-01T00:00:00.000Z',
    item_count: 4,
    items: [
      {
        id: 'b-1',
        set_id: 'toeic-business-02',
        term: 'Negotiation',
        definition: 'Discussion aimed at reaching an agreement.',
        ipa: '/nɪˌɡoʊ.ʃiˈeɪ.ʃən/',
        example_sentence: 'Successful negotiation requires mutual compromise.',
        vietnamese_translation: 'Cuộc đàm phán, thương lượng',
        synonyms: ['bargaining', 'discussion'],
        created_at: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'b-2',
        set_id: 'toeic-business-02',
        term: 'Consensus',
        definition: 'A general agreement among members of a group.',
        ipa: '/kənˈsen.səs/',
        example_sentence: 'The committee reached a consensus regarding the annual budget.',
        vietnamese_translation: 'Sự đồng thuận chung',
        synonyms: ['agreement', 'harmony'],
        created_at: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'b-3',
        set_id: 'toeic-business-02',
        term: 'Collaborate',
        definition: 'Work jointly on an activity or project.',
        ipa: '/kəˈlæb.ə.reɪt/',
        example_sentence: 'Teams from two departments collaborated to launch the product.',
        vietnamese_translation: 'Cộng tác, hợp tác làm việc',
        synonyms: ['cooperate', 'partner'],
        created_at: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'b-4',
        set_id: 'toeic-business-02',
        term: 'Optimization',
        definition: 'The action of making the best or most effective use of a situation or resource.',
        ipa: '/ˌɑːp.tə.məˈzeɪ.ʃən/',
        example_sentence: 'Code optimization significantly reduced server load.',
        vietnamese_translation: 'Sự tối ưu hóa',
        synonyms: ['refinement', 'improvement'],
        created_at: '2026-01-01T00:00:00.000Z',
      },
    ],
  },
]
